lib: [
  "_build/install/default/lib/mpp/META"
  "_build/install/default/lib/mpp/dune-package"
  "_build/install/default/lib/mpp/mpp.a"
  "_build/install/default/lib/mpp/mpp.cma"
  "_build/install/default/lib/mpp/mpp.cmi"
  "_build/install/default/lib/mpp/mpp.cmt"
  "_build/install/default/lib/mpp/mpp.cmx"
  "_build/install/default/lib/mpp/mpp.cmxa"
  "_build/install/default/lib/mpp/mpp.ml"
  "_build/install/default/lib/mpp/mpp__Mppx.cmi"
  "_build/install/default/lib/mpp/mpp__Mppx.cmt"
  "_build/install/default/lib/mpp/mpp__Mppx.cmx"
  "_build/install/default/lib/mpp/mppx.ml"
  "_build/install/default/lib/mpp/opam"
]
libexec: [
  "_build/install/default/lib/mpp/mpp.cmxs"
  "_build/install/default/lib/mpp/ppx.exe"
]
doc: [
  "_build/install/default/doc/mpp/LICENSE"
]
